version: '3'
name: hab-eat-server

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.5-alpine
    restart: always
    ports:
      - '80:80'
      - '433:433'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-connection
    depends_on:
      - api-server
    deploy:
      resources:
        limits:
          memory: 128M
  api-server:
    image: abjin/hab-eat-api-server:latest
    container_name: api-server
    expose:
      - '3000'
    networks:
      - nginx-connection
      - api-network
    depends_on:
      - ai-server
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 216M
  ai-server:
    image: abjin/hab-eat-ai-api-server:latest
    container_name: ai-server
    networks:
      - api-network
    deploy:
      resources:
        limits:
          memory: 512M
networks:
  nginx-connection:
  api-network:
